### PR TITLE
Fixed error when selecting user type if an empty string is entered

### PR DESCRIPTION
**Pull request by NasserNgandu**
When you have to choose the type of user, if a user does not type anything by clicking on enter the code generates an error.

### CODE REVIEW

**Comment by Revisto** [comment]
Hi, its' kinda weird to see a pull request on one of my university tasks but here we are :D
thanks for your changes, i think its the best to remove .pyc files and then I can merge.

**Comment by NasserNgandu** [comment]
LOL, I wanted to help someone from my university who has the same task, I said to myself why not even add a small stone to the building.

**Comment by Revisto** [comment]
Great :D well thank you so much.

**Comment by NasserNgandu** [comment]
Thank you very much too

**Pull request merged**
